from collections.abc import Buffer, Callable, Coroutine
from typing import Concatenate, NoReturn, Self

class EagerRoutine[Payload: Buffer, Result](Coroutine[None, None, Result]):
    def __init__[**P](
        self,
        func: Callable[Concatenate[Payload, P], Result],
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> None: ...
    def __call__(self, data: Payload, /) -> Self: ...
    def __await__(self) -> NoReturn: ...
    def send(self, _) -> NoReturn: ...
    def throw(self, *_) -> NoReturn: ...
    def close(self) -> NoReturn: ...
