from collections.abc import Buffer
from typing import NewType, Protocol

Uint32 = NewType("Uint32", int)
Uint64 = NewType("Uint64", int)
Uint128 = NewType("Uint128", int)

class Hasher[T: int](Protocol):
    def __new__(cls, data: str | Buffer, /, seed: int = ...) -> T: ...
    def digest(self) -> bytes: ...

class CityHash64WithSeed(Hasher[Uint64]): ...
class CityHash128WithSeed(Hasher[Uint128]): ...
