from collections.abc import Buffer
from typing import Protocol

class Hasher(Protocol):
    def __new__(cls, data: str | Buffer, /, seed: int = ...) -> int: ...
    def digest(self) -> bytes: ...

class CityHash64WithSeed(Hasher): ...
class CityHash128WithSeed(Hasher): ...
