from collections.abc import Buffer

from cityhash import Uint64, Uint128

def hash64_int(data: str | Buffer, /, seed: int = ...) -> Uint64: ...
def hash128_int(data: str | Buffer, /, seed: int = ...) -> Uint128: ...
