from _hashlib import HASH
from collections.abc import Buffer

class siphash13(HASH):  # noqa: N801
    def __init__(self, data: Buffer = b"", /, *, key: Buffer = b"") -> None: ...
    def intdigest(self) -> int: ...

class siphash24(HASH):  # noqa: N801
    def __init__(self, data: Buffer = b"", /, *, key: Buffer = b"") -> None: ...
    def intdigest(self) -> int: ...
