name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    branches: main
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - uses: PyO3/maturin-action@v1.8.3
        with:
          command: publish
          args: --release
