name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: Release Type
        type: choice
        default: patch
        options: [patch, minor, major]

permissions: {}

jobs:
  main:
    uses: winstxnhdw/gxhash/.github/workflows/main.yml@main
    secrets: inherit

  python:
    uses: winstxnhdw/gxhash/.github/workflows/python.yml@main

  release:
    needs: [main, python]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          show-progress: false
          fetch-depth: 0
          ssh-key: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Install commitizen
        uses: commitizen-tools/setup-cz@v0.7.0

      - name: Get next ${{ inputs.release-type }} revision
        id: get-revision
        run: echo "revision=$(cz bump --get-next --increment "$RELEASE_TYPE")" > "$GITHUB_OUTPUT"
        env:
          RELEASE_TYPE: ${{ inputs.release-type }}

      - name: Update gxhash-tests lockfile
        run: cargo update --manifest-path tests/Cargo.toml

      - name: Update gxhash-perf lockfile
        run: cargo update --manifest-path perf/Cargo.toml

      - name: Stage lockfile updates
        run: git add "**/Cargo.lock"

      - name: Create bump and changelog
        env:
          RELEASE_TYPE: ${{ inputs.release-type }}
        run: >-
          cz bump
          --increment "$RELEASE_TYPE"
          --yes
          --changelog
          --git-output-to-stderr
          --changelog-to-stdout | tail -n +2 > body.md

      - name: Push changelog and tag
        id: push
        run: git push --atomic origin main "$REVISION"
        env:
          REVISION: ${{ steps.get-revision.outputs.revision }}

      - name: Create GitHub release ${{ steps.get-revision.outputs.revision }}
        run: gh release create "$REVISION" -t "$REVISION" -F body.md --verify-tag
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          REVISION: ${{ steps.get-revision.outputs.revision }}

      - name: Revert changelog and tag on failure
        if: failure() && steps.push.outcome == 'success'
        env:
          REVISION: ${{ steps.get-revision.outputs.revision }}
        run: |
          git revert --no-commit HEAD
          git commit -m "revert: release $REVISION"
          git push --atomic origin main --delete "$REVISION"
